In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\radha\onedrive\conda\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\radha\onedrive\conda\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\radha\onedrive\conda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\radha\onedrive\conda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\radha\onedrive\conda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\radha\onedrive\conda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

Create a pandas series

In [6]:
s = pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

Create Series with custom index

In [8]:
s1 = pd.Series([10,20,30,40], index = ['a','b','c','d'])
s1

a    10
b    20
c    30
d    40
dtype: int64

Create Series from dictionary

In [9]:
data = {'a':10,'b':20,'c':30,'d':40}
s2 = pd.Series(data)
s2

a    10
b    20
c    30
d    40
dtype: int64

Make dataframe from dictionary

In [12]:
print(s2['b'])

20

DataFrame with custom index

In [14]:
data = {
    'Math':[84,64,89,65],
    'Science':[78,98,78,89]
}
df = pd.DataFrame(data)         # indexing 0,1,2,3 came by defult.
df

   Math  Science
0    84       78
1    64       98
2    89       78
3    65       89

In [15]:
df1 = pd.DataFrame(data, index = ['a','b','c','d'])    # here we gave indexing.
df1

   Math  Science
a    84       78
b    64       98
c    89       78
d    65       89

DataFrame from Series

In [16]:
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])

df = pd.DataFrame({'col1': s1, 'col2': s2})
df

   col1  col2
0     1     4
1     2     5
2     3     6

In [21]:
df1 = pd.DataFrame({
    'ShipmentID': [1001, 1002, 1003, 1004, 1005],
    'Origin': ['NY', 'SF', 'Dallas', 'Chicago', 'Miami'],
    'Destination': ['Boston', 'Seattle', 'Houston', 'Atlanta', 'Denver'],
    'Weight_kg': [12.5, 8.0, 15.0, 7.5, 10.0],
    'Fragile': [True, False, True, False, True],
    'Status': ['Delivered', 'In Transit', 'Delayed', 'Delivered', 'Delayed']
})

In [22]:
df1

   ShipmentID   Origin Destination  Weight_kg  Fragile      Status
0        1001       NY      Boston       12.5     True   Delivered
1        1002       SF     Seattle        8.0    False  In Transit
2        1003   Dallas     Houston       15.0     True     Delayed
3        1004  Chicago     Atlanta        7.5    False   Delivered
4        1005    Miami      Denver       10.0     True     Delayed

In [23]:
df1.shape

(5, 6)

In [24]:
df1.dtypes

ShipmentID       int64
Origin          object
Destination     object
Weight_kg      float64
Fragile           bool
Status          object
dtype: object

In [25]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ShipmentID   5 non-null      int64
 1   Origin       5 non-null      object
 2   Destination  5 non-null      object
 3   Weight_kg    5 non-null      float64
 4   Fragile      5 non-null      bool
 5   Status       5 non-null      object
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 337.0+ bytes

In [26]:
df1['ShipmentID']            # here the output is Series

0    1001
1    1002
2    1003
3    1004
4    1005
Name: ShipmentID, dtype: int64

In [27]:
df1['Status']

0     Delivered
1    In Transit
2       Delayed
3     Delivered
4       Delayed
Name: Status, dtype: object

In [29]:
df1['Status'].value_counts()                    # important function

Status
Delivered     2
Delayed       2
In Transit    1
Name: count, dtype: int64

In [28]:
df1.columns

Index(['ShipmentID', 'Origin', 'Destination', 'Weight_kg', 'Fragile',
       'Status'],
      dtype='object')

In [31]:
data = {
    'A': [101,102,103],
    'B':[201,202,203],
    'C': [301,302,303]
    }
s1 = pd.DataFrame(data, index=['a','b','c'])
s1

     A    B    C
a  101  201  301
b  102  202  302
c  103  203  303

Select column

In [32]:
s1['B']

a    201
b    202
c    203
Name: B, dtype: int64

Multiple columns

In [33]:
s1[['B','C']]

     B    C
a  201  301
b  202  302
c  203  303

loc (label-based)

In [34]:
s1.loc['a']

A    101
B    201
C    301
Name: a, dtype: int64

In [35]:
s1.loc['c']

A    103
B    203
C    303
Name: c, dtype: int64

In [39]:
print(s1.loc['b','B'])

202

In [40]:
print(s1.loc['c','B'])

203

iloc (index-based)

In [41]:
s1.iloc[0]

A    101
B    201
C    301
Name: a, dtype: int64

In [42]:
s1.iloc[1]

A    102
B    202
C    302
Name: b, dtype: int64

In [43]:
print(s1.iloc[1,1])

202

In [44]:
df1

   ShipmentID   Origin Destination  Weight_kg  Fragile      Status
0        1001       NY      Boston       12.5     True   Delivered
1        1002       SF     Seattle        8.0    False  In Transit
2        1003   Dallas     Houston       15.0     True     Delayed
3        1004  Chicago     Atlanta        7.5    False   Delivered
4        1005    Miami      Denver       10.0     True     Delayed

How will you filter rows where Weight > 10 using loc?

In [45]:
df1.loc[df1['Weight_kg']>10]

   ShipmentID  Origin Destination  Weight_kg  Fragile     Status
0        1001      NY      Boston       12.5     True  Delivered
2        1003  Dallas     Houston       15.0     True    Delayed

How will you select only 'Destination' column?

In [46]:
df1['Destination']

0     Boston
1    Seattle
2    Houston
3    Atlanta
4     Denver
Name: Destination, dtype: object

Cost = Weight * 10?

In [47]:
df1['Cost'] = df1['Weight_kg']*10               #created new column

In [48]:
df1

   ShipmentID   Origin Destination  Weight_kg  Fragile      Status   Cost
0        1001       NY      Boston       12.5     True   Delivered  125.0
1        1002       SF     Seattle        8.0    False  In Transit   80.0
2        1003   Dallas     Houston       15.0     True     Delayed  150.0
3        1004  Chicago     Atlanta        7.5    False   Delivered   75.0
4        1005    Miami      Denver       10.0     True     Delayed  100.0

In [6]:
df

   col1  col2
0     1     4
1     2     5
2     3     6

In [54]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Amit', 'Sara', 'John', 'Priya', 'Ravi'],
    'Math': [80, 90, 75, 85, 60],
    'Science': [70, 95, 80, 75, 65],
    'Passed': [True, True, True, True, False]
})

In [55]:
df

    Name  Math  Science  Passed
0   Amit    80       70    True
1   Sara    90       95    True
2   John    75       80    True
3  Priya    85       75    True
4   Ravi    60       65   False

How many rows and columns are there?

In [56]:
df.shape                              # can also use info

(5, 4)

What are the column names?

In [57]:
df.columns

Index(['Name', 'Math', 'Science', 'Passed'], dtype='object')

What is the data type of each column?

In [58]:
df.dtypes

Name       object
Math        int64
Science     int64
Passed       bool
dtype: object

How will you select only the Math marks column?

In [59]:
df['Math']

0    80
1    90
2    75
3    85
4    60
Name: Math, dtype: int64

How will you select Name and Science columns together?

In [60]:
df[['Math','Science']]

   Math  Science
0    80       70
1    90       95
2    75       80
3    85       75
4    60       65

How will you get the first row?

In [61]:
df.iloc[0]

Name       Amit
Math         80
Science      70
Passed     True
Name: 0, dtype: object

How will you get the last row?

In [62]:
df.iloc[-1]

Name        Ravi
Math          60
Science       65
Passed     False
Name: 4, dtype: object

How will you get the 2nd row and 3rd column value?

In [63]:
print(df.iloc[1,2])

95

How will you get first 3 rows?

In [65]:
df.iloc[0:3]

   Name  Math  Science  Passed
0  Amit    80       70    True
1  Sara    90       95    True
2  John    75       80    True

How will you get rows 2 to 4 and columns 1 to 2?

In [66]:
df.iloc[1:4,0:2]

    Name  Math
1   Sara    90
2   John    75
3  Priya    85

How will you get all students who passed?

In [69]:
df[df['Passed']==True]

    Name  Math  Science  Passed
0   Amit    80       70    True
1   Sara    90       95    True
2   John    75       80    True
3  Priya    85       75    True

How will you get students with Math > 80 AND Science > 80?

In [78]:
df[(df['Math']>80) & (df['Science']>80)]

   Name  Math  Science  Passed
1  Sara    90       95    True

How will you create a new column Total = Math + Science?

In [80]:
df['Total'] = df['Math']+df['Science']     
df

    Name  Math  Science  Passed  Total
0   Amit    80       70    True    150
1   Sara    90       95    True    185
2   John    75       80    True    155
3  Priya    85       75    True    160
4   Ravi    60       65   False    125

How will you create Average marks?

In [83]:
df['Average'] = df['Total']/2
df

    Name  Math  Science  Passed  Total  Average
0   Amit    80       70    True    150     75.0
1   Sara    90       95    True    185     92.5
2   John    75       80    True    155     77.5
3  Priya    85       75    True    160     80.0
4   Ravi    60       65   False    125     62.5

Above 80 → Excellent, else Average. Create new column called category

In [87]:
def remark(marks):
    if marks>80:
        return "Excellent"
    else:
        return "Average"
df['Category'] = df['Average'].apply(remark)        
df

    Name  Math  Science  Passed  Total  Average   Category
0   Amit    80       70    True    150     75.0    Average
1   Sara    90       95    True    185     92.5  Excellent
2   John    75       80    True    155     77.5    Average
3  Priya    85       75    True    160     80.0    Average
4   Ravi    60       65   False    125     62.5    Average

How will you label Passed column:

True → "Yes", False → "No"

In [89]:
def grade(result):
    if result==True:
        return"Yes"
    else:
        return "No"
df['Lable']=df['Passed'].apply(grade)

In [90]:
df

    Name  Math  Science  Passed  Total  Average   Category Lable
0   Amit    80       70    True    150     75.0    Average   Yes
1   Sara    90       95    True    185     92.5  Excellent   Yes
2   John    75       80    True    155     77.5    Average   Yes
3  Priya    85       75    True    160     80.0    Average   Yes
4   Ravi    60       65   False    125     62.5    Average    No

How will you rename column Math → Maths?

In [93]:
df[df['Math'] == df['Maths']]

KeyError: 'Maths'

How will you drop column Science?

What is the average Math score of class?

How many students passed?

read_csv