
# NumPy & Pandas Lab (Questions) — v2
**Duration:** ~2 hours

## Setup
Import NumPy and Pandas as needed in the cell below.

In [1]:
import numpy as np
import pandas as pd

# NumPy: Intro & Array Creation

**Exercise 1:** In comments, note two benefits of NumPy over plain Python lists (e.g., speed via vectorization, convenient broadcasting). Then create an array `a = [1,2,3]` and print `2*a`.

In [4]:
a = np.array([1,2,3])
print(2*a)

[2 4 6]

**Exercise 2:** Create a 1D array from the list [1,2,3] and print its Python type and NumPy dtype.

In [10]:
a = np.array([1,2,3])
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64

**Exercise 3:** Create a 3x3 array of zeros with integer dtype and print it.

In [25]:
b = np.zeros((3,3)).astype(int)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

**Exercise 4:** Create a 2x3 array of ones with float dtype and print its shape and dtype.

In [26]:
c = np.ones((2,3))
print(c.shape)
print(c.dtype)

(2, 3)
float64

**Exercise 5:** Using `arange`, create `[5,10,15,20]`.

In [29]:
d = np.arange(5,21,5)
d

array([ 5, 10, 15, 20])

**Exercise 6:** Using `linspace`, create 5 evenly spaced numbers from 0 to 1 (inclusive).

In [36]:
e = np.linspace(0,1,5)
print(e)

[0.   0.25 0.5  0.75 1.  ]

# NumPy: Properties & Element-wise Operations

**Exercise 1:** Given `arr = np.array([[1,2,3],[4,5,6]])`, print its `shape`, `ndim`, and `dtype`.

In [42]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64

**Exercise 2:** Cast the above `arr` to float dtype and print its dtype.

In [47]:
arr = arr.astype(float)
print(arr.dtype)

float64

**Exercise 3:** Perform element-wise addition, subtraction, multiplication, and division between `a=np.array([10,20,30])` and `b=np.array([1,2,3])` and print all results.

In [52]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]

**Exercise 4:** For `arr = np.array([1,2,3,4])`, compute `arr + 10` and `arr * 2` and print both.

In [54]:
arr = np.array([1,2,3,4])
print(arr+10)
print(arr*2)

[11 12 13 14]
[2 4 6 8]

# NumPy: Aggregations

**Exercise 1:** Create `arr = np.arange(1,10).reshape(3,3)` and print the overall `sum()`, `mean()`, and `std()`.

In [60]:
arr = np.arange(1,10).reshape(3,3)
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))

45
5.0
2.581988897471611

**Exercise 2:** Using the same `arr`, print column-wise sums (axis=0) and row-wise means (axis=1).

In [62]:
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[12 15 18]
[ 6 15 24]

# Pandas: Series Creation, Indexing, Slicing, Vector Ops

**Exercise 1:** Create a Series from the list `[10,20,30]` with index `['a','b','c']` and print it.

In [68]:
a = pd.Series([10,20,30],index=['a','b','c'])
a

a    10
b    20
c    30
dtype: int64

**Exercise 2:** Create a Series from the dict `{'apples':3,'bananas':2,'oranges':5}` and print the value for 'bananas'.

In [72]:
data = {'apples':3,'bananas':2,'oranges':5}
b = pd.Series(data)
print(b['bananas'])

2

**Exercise 3:** From `s = pd.Series([10,20,30,40,50], index=list('abcde'))`, slice from label 'b' to 'd' and print.

In [74]:
s = pd.Series([10,20,30,40,50], index=list('abcde'))
print(s['b':'d'])

b    20
c    30
d    40
dtype: int64

**Exercise 4:** Create `s = pd.Series([1,2,3,4])` and print `s*2 + 1`.

In [75]:
s = pd.Series([1,2,3,4])
print(s*2+1)

0    3
1    5
2    7
3    9
dtype: int64

# Pandas: DataFrame Creation & Overview

**Exercise 1:** Create a DataFrame from a dict with columns `name`, `age`, `score` (3 rows) and print `head()`.

In [80]:
Data = {
    'Name':['Meena','Teena','Reena'],
    'Age':[13,15,19],
    'Score':[89,67,76]
}
df = pd.DataFrame(Data)
df.head()

    Name  Age  Score
0  Meena   13     89
1  Teena   15     67
2  Reena   19     76

**Exercise 2:** Create a DataFrame from a list of dicts with the same columns as above and print `tail()`.

In [83]:
Data = [
    {'name':'Teena','age':15,'score':77},
    {'name':'Meena','age':17,'score':89},
    {'name':'Reena','age':18,'score':87}
]
df = pd.DataFrame(Data)
df.tail()                # tail give next 5 rows

    name  age  score
0  Teena   15     77
1  Meena   17     89
2  Reena   18     87

**Exercise 3:** Create a DataFrame `df_csv` *in memory* with columns name, age, score (3 rows) and call `info()`.

In [85]:
df_csv = [
    {'name':'Teena','age':15,'score':77},
    {'name':'Meena','age':17,'score':89},
    {'name':'Reena','age':18,'score':87}
]
df = pd.DataFrame(df_csv)
df.info()                # give not null value and no.of rows

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   score   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

**Exercise 4:** On the same `df_csv`, call `describe()` and print the result.

In [87]:
df.describe()               # gives statical numbers

             age      score
count   3.000000   3.000000
mean   16.666667  84.333333
std     1.527525   6.429101
min    15.000000  77.000000
25%    16.000000  82.000000
50%    17.000000  87.000000
75%    17.500000  88.000000
max    18.000000  89.000000

# Pandas: Selecting Data with loc[] and iloc[]

**Exercise 1:** Using `df = pd.DataFrame({'name':['Ana','Ben','Cara'],'age':[20,23,21],'score':[81,67,90]})`, select rows where age>20 and only columns `name` and `score` using `loc`.

In [88]:
df = pd.DataFrame({'name':['Ana','Ben','Cara'],'age':[20,23,21],'score':[81,67,90]})
df

   name  age  score
0   Ana   20     81
1   Ben   23     67
2  Cara   21     90

In [91]:
df.loc[df['age']>20,['name','score']]

   name  score
1   Ben     67
2  Cara     90

**Exercise 2:** From the same `df`, select the first two rows and first two columns using `iloc`.

In [92]:
df

   name  age  score
0   Ana   20     81
1   Ben   23     67
2  Cara   21     90

In [94]:
df.iloc[0:2,0:2]

  name  age
0  Ana   20
1  Ben   23

**Exercise 3:** Set `df.index` to `['s1','s2','s3']` and select the row with label `'s2'` using `loc`.

In [96]:
df.index=['s1','s2','s3']
df.loc['s2']

name     Ben
age       23
score     67
Name: s2, dtype: object

# Pandas: Adding & Removing Columns

**Exercise 1:** Add a column `passed` that is True if score>=80 else False, for `df = pd.DataFrame({'name':['Ana','Ben','Cara'],'score':[81,67,90]})`.

In [101]:
df = pd.DataFrame({'name':['Ana','Ben','Cara'],'score':[81,67,90]})
def remark(score):
    if score>=80: 
        return "True"
    else:
        return "False"
df['passed']=df['score'].apply(remark)
df

   name  score passed
0   Ana     81   True
1   Ben     67  False
2  Cara     90   True

**Exercise 2:** Remove column `age` from `df` (if present) using `drop(..., axis=1)` and print the remaining columns.

# Pandas: Filtering Rows with Conditions

**Exercise 1:** Given `df = pd.DataFrame({'name':['Ana','Ben','Cara','Dan'],'score':[81,67,90,74]})`, select rows with `score` between 70 and 90 (inclusive).

# Pandas: Renaming Columns & Updating Values

**Exercise 1:** Rename the column `score` to `marks` for a DataFrame and print new columns.

**Exercise 2:** Increase `marks` by 5 for the row where `name=='Ana'` and print the updated row.

# Pandas: Sorting by Column(s)

**Exercise 1:** Sort `df = pd.DataFrame({'name':['Ana','Ben','Cara'],'marks':[86,67,90]})` by `marks` descending, then by `name` ascending, and print the result.

# Pandas: Handling Missing Data (isnull, dropna, fillna)

**Exercise 1:** Create `df = pd.DataFrame({'a':[1,None,3],'b':[None,2,2],'c':[5,6,None]})` and print the count of missing values in each column.

**Exercise 2:** From the same `df`, drop rows where column `a` is missing using `dropna(subset=['a'])` and print the result.

**Exercise 3:** Fill missing values in column `b` with the column mean and print the updated DataFrame.